### ISSUE TITLE
GreenPipes NuGet Package incorrectly specifies patch-level

### ISSUE THREAD

**Issue by wilson0x4d** [MassTransit/GreenPipes#6]
The specification of a patch level for .NET Framework 4.5 (ie. 4.5**.2**) makes it impossible for us to target a most-common major.minor in our own solutions because GreenPipes "requires" .NET 4.5.2 ... (ie. where we target .NET 4.5 in our packaging, we only assign patch-level to EXE projects, since this is what ultimately determines which CLR patch-level is loaded at runtime, not the patch level specified in any nuspec.)

To clarify:

When you Target and/or Package  for .NET Framework 4.5 we can target all patch levels and still use your nuget package, such as .NET 4.5, 4.5.1, 4.5.2, 4.6, 4.7, etc.

When you Target and/or Package for .NET Framwork 4.5.2 (_note the patch-level specification_) we can only include your package when we also target .NET 4.5.2 or later in our nuspec. Thus, the current version constraint precludes our creating a package which targets the broader .NET Framework 4.5 version.) This has the adverse effect of preventing us from using a platform target of .NET 4.5 in our shared library builds which reference these packages.

Again, we assign/assert/require a Framework patch-level by virtue of the Framework Target of our EXE projects. Class-libraries and their nuspecs necessarily always target the broader Framework Targets (ie. no patch-level.

Can you please make it a matter of practice to target the lowest-supported major+minor (and avoid the specification of a Framework patch-level unless it is **absolutely necessary** to address a bug)?

We do not have a workaround for this, this framework patch-level constraint breaks our builds and we're unable to leverage the latest MassTransit packages without also taking on this dependency.

Thanks for any assist.. let me know if I can clarify further.

**Comment by phatboyg** [comment]
.NET 4.5.2 is the only supported version of .NET 4.5 by Microsoft.
